// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKd6m68NBJLuyZSJtd8Exz4DSJ7kH3tOk',
    appId: '1:674964971272:web:70c034e8f982634f08d6bd',
    messagingSenderId: '674964971272',
    projectId: 'uas-ticket-movie-app',
    authDomain: 'uas-ticket-movie-app.firebaseapp.com',
    storageBucket: 'uas-ticket-movie-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDq5aF4173B2uKNB_LZ1Tmj7E7NRyIYH8',
    appId: '1:674964971272:android:aa03561a177271f508d6bd',
    messagingSenderId: '674964971272',
    projectId: 'uas-ticket-movie-app',
    storageBucket: 'uas-ticket-movie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHu6990Pt6sS-P-d9CW8P5XiCcS2zg6xE',
    appId: '1:674964971272:ios:ef56b75475695f3a08d6bd',
    messagingSenderId: '674964971272',
    projectId: 'uas-ticket-movie-app',
    storageBucket: 'uas-ticket-movie-app.appspot.com',
    iosClientId: '674964971272-lsm63a7rok0lthc7lso0q63bm24ikk64.apps.googleusercontent.com',
    iosBundleId: 'com.example.uas1972025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHu6990Pt6sS-P-d9CW8P5XiCcS2zg6xE',
    appId: '1:674964971272:ios:ef56b75475695f3a08d6bd',
    messagingSenderId: '674964971272',
    projectId: 'uas-ticket-movie-app',
    storageBucket: 'uas-ticket-movie-app.appspot.com',
    iosClientId: '674964971272-lsm63a7rok0lthc7lso0q63bm24ikk64.apps.googleusercontent.com',
    iosBundleId: 'com.example.uas1972025',
  );
}
